name: npm install
description: npm install
inputs:
  working-directory:
    description: working-directory
    required: false
    default: "."

  # TODO? RENAME? ls_cli_options
  ls_options:
    description: ls options
    required: false
    # in windows, la does NOT work
    default: "-la"

runs:
  using: composite
  steps:
    - name: ls
      shell: bash
      run: ls ${{ inputs.ls_options }} ${{ inputs.working-directory }}

    - name: npm run setup:ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm run setup:ci --if-present

    - name: npm install
      shell: bash
      run: npm clean-install --prefix ${{ inputs.working-directory }}

    - name: ls ./node_modules
      shell: bash
      run: ls ${{ inputs.ls_options }} ${{ inputs.working-directory }}/node_modules
