name: npm audit
description: npm audit

inputs:
  working-directory:
    description: working-directory
    required: false
    default: "."

  npm_audit_cli_options:
    description: "Must be one or more of: dev, optional, peer"
    required: false
    default: "--omit=dev"

  continue-on-error:
    description: continue on error
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: npm audit
      shell: bash
      run: npm audit ${{ inputs.npm_audit_cli_options }} --prefix ${{ inputs.working-directory }}

    # NOTE: continue-on-error is set to true to avoid failing the entire workflow if vulnerabilities are found on devDependencies.
    # This allows us to report vulnerabilities without blocking the workflow, which can be useful for monitoring and addressing issues over time.
    - name: npm audit
      shell: bash
      run: npm audit ${{ inputs.npm_audit_cli_options }} --prefix ${{ inputs.working-directory }}
      continue-on-error: ${{ inputs.continue-on-error == 'true'}}
