name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  npm_run_lint:
    uses: ./.github/actions/npm_run_script.yml
    with:
      script: lint
