name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  npm_run_lint:
    uses: ./.github/workflows/npm_run.yml
    with:
      script: lint
