name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  npm_run_lint:
    name: npm lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/npm_run
        with:
          script: lint
