name: "[C]ontinuous [I]ntegration"

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/run_script.yml
    with:
      script: lint

  codeQL:
    needs: lint
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - actions
          - javascript

    name: "CodeQL: ${{ matrix.language }}"
    uses: percebus/github-actions-compliance/.github/workflows/codeql_analyze.yml@main
    with:
      language: ${{ matrix.language }}
