name: npm audit

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      working-directory:
        type: string
        description: Working directory
        required: false
        default: .

      npm_audit_cli_options:
        type: string
        description: npm audit CLI options
        required: false
        default: "--omit=dev"

  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      working-directory:
        type: string
        description: Working directory
        required: false
        default: .

      npm_audit_cli_options:
        type: string
        description: CLI arguments to pass to the action
        required: false
        default: "--omit=dev"

# NOTE: Set in final file
# permissions:
#   contents: read
#   pull-requests: read

jobs:
  npm_audit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ inputs.ssh-private-key }}

      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: percebus/github-actions-npm/.github/actions/install@main
      - uses: percebus/github-actions-npm/.github/actions/audit@main
        with:
          working-directory: ${{ inputs.working-directory }}
          npm_audit_cli_options: ${{ inputs.npm_audit_cli_options }}
