name: npm audit

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      cli_arguments:
        type: string
        description: CLI arguments to pass to the action
        required: false
        default: "--omit=dev"

  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      cli_arguments:
        type: string
        description: CLI arguments to pass to the action
        required: false
        default: "--omit=dev"

# NOTE: Set in final file
# permissions:
#   contents: read
#   pull-requests: read

jobs:
  npm_audit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ inputs.ssh-private-key }}

      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: percebus/github-actions-npm/.github/actions/install@main

      # - uses: percebus/github-actions-npm/.github/actions/audit@main  # TODO
      # TODO XXX vvv
      - name: npm audit
        # run: npm audit ${{ inputs.cli_arguments }} # FIXME why doesn't this work?
        run: npm audit --omit=dev
        continue-on-error: true
