name: Dependencies Review & Audit

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      ssh-private-key:
        description: SSH private key
        required: false

    inputs:
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      working-directory:
        type: string
        description: Working directory
        required: false
        default: .

      continue-on-error:
        type: boolean
        description: continue on error
        required: false
        default: true

permissions:
  contents: read

jobs:
  dependency-review:
    name: compliance
    uses: percebus/github-actions-compliance/.github/workflows/dependency-review.yml@main
    permissions:
      contents: read
      pull-requests: read
    # secrets:
    #   ssh-private-key: ${{ secrets.ssh-private-key }} # TODO
    with:
      ssh-private-key: ${{ inputs.ssh-private-key }} # XXX

  # NOTE: is this job redundant?
  # does dependency-review-action accomplish the same, and more?
  audit:
    name: npm
    uses: percebus/github-actions-npm/.github/workflows/audit.yml@main
    secrets:
      ssh-private-key: ${{ secrets.ssh-private-key }}
    with:
      ssh-private-key: ${{ inputs.ssh-private-key }} # XXX
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: ${{ inputs.continue-on-error }}
