name: Dependencies Review & Audit

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      npm_audit_cli_arguments:
        type: string
        description: CLI arguments to pass to the action
        required: false
        default: "--omit=dev"

# XXX? Should this be added on pull_request instead?
permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    uses: percebus/github-actions-compliance/.github/workflows/dependency-review.yml@main
    with:
      ssh-private-key: ${{ inputs.ssh-private-key }}

  # NOTE: is this job redundant?
  # does dependency-review-action accomplish the same, and more?
  audit:
    uses: percebus/github-actions-npm/.github/workflows/audit.yml@main
    with:
      ssh-private-key: ${{ inputs.ssh-private-key }}
      cli_arguments: ${{ inputs.npm_audit_cli_arguments }}
