name: npm audit
on:
  push:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

jobs:
  # NOTE: is this job redundant?
  # does dependency-review-action accomplish the same, and more?
  npm_audit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ github.event.inputs.ssh-private-key }}

      - uses: percebus/github-actions-node/.github/actions/node_setup@main
      - uses: percebus/github-actions-npm/.github/actions/npm_install@main

      - name: npm audit
        run: npm audit
        continue-on-error: true
