name: Test workflows/audit

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  default:
    name: default
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/audit.yml

  #
  working-directory__matrix:
    needs: default
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        working-directory:
          - sub-package

    name: "prefix ${{ matrix.working-directory }}"
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/audit.yml
    with:
      working-directory: node/${{ matrix.working-directory }}
