name: Test workflows/npm_test
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

env: # XXX default should NOT have values
  REPORTER: jest-junit
  FILE_PATTERN: junit.xml

jobs:
  default:
    name: default
    uses: ./.github/workflows/npm_test.yml
    # with: # XXX default should NOT have values
    #   reporter: ${{ env.REPORTER }}
    #   files_pattern: ${{ env.FILE_PATTERN }}

  filt_pattern_matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        files_pattern:
          - junit.xml
          - junit*.xml
          - *.xml

    name: "file_pattern: ${{ matrix.files_pattern }}"
    uses: ./.github/workflows/npm_test.yml
    with:
      reporter: ${{ env.REPORTER }}
      files_pattern: ${{ matrix.files_pattern }}

  os_matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        OS:
          - ubuntu-latest

          #
          # FIXME not working
          # "Container action is only supported for Linux"
          # - windows-latest
          # - macOS-latest

    name: "@ ${{ matrix.OS }}"
    uses: ./.github/workflows/npm_test.yml
    with:
      runs-on: ${{ matrix.OS }}
      reporter: ${{ env.REPORTER }}
      files_pattern: ${{ env.FILE_PATTERN }}
