name: Test workflows/npm_test
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  default:
    name: default
    uses: ./.github/workflows/npm_test.yml
    with: # XXX default should NOT have values
      reporter: jest-junit
      files_pattern: junit.xml

  reporter_matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        reporter:
          - ""
          - jest-junit

    name: "script: ${{ matrix.reporter }}"
    uses: ./.github/workflows/npm_test.yml
    with:
      reporter: ${{ matrix.reporter }}
      files_pattern: junit.xml

  os_matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        OS:
          - ubuntu-latest

          #
          # FIXME not working
          # "Container action is only supported for Linux"
          # - windows-latest
          # - macOS-latest

    name: "@ ${{ matrix.OS }}"
    uses: ./.github/workflows/npm_test.yml
    with:
      runs-on: ${{ matrix.OS }}
      reporter: jest-junit
      files_pattern: junit.xml
