name: Test workflows/npm_test

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  default:
    name: default
    uses: ./.github/workflows/npm_test.yml

  reporter__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        reporter:
          - ""
          - jest-junit

    name: "reporter: ${{ matrix.reporter }}"
    uses: ./.github/workflows/npm_test.yml
    with:
      reporter: ${{ matrix.reporter }}

  file_pattern__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        files_pattern:
          - junit.xml
          - junit*.xml
          - "*.xml"

    name: "file_pattern: ${{ matrix.files_pattern }}"
    uses: ./.github/workflows/npm_test.yml
    with:
      files_pattern: ${{ matrix.files_pattern }}

  working-directory___matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        working-directory:
          - .
          - node/sub-package

        OS:
          - ubuntu-latest

          #
          # FIXME not working
          # "Container action is only supported for Linux"
          # - windows-latest
          # - macOS-latest

    name: "prefix ${{ matrix.working-directory }} @ ${{ matrix.OS }}"
    uses: ./.github/workflows/npm_test.yml
    with:
      # windows complains about EoL characters in the script
      runs-on: ${{ matrix.OS }}
      working-directory: ${{ matrix.working-directory }}
