name: Test actions/npm_install

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: ./.github/actions/npm_install

  ls_options__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        ls_options:
          - "-la"
          - "-l"
          - "-a"
        OS:
          - ubuntu-latest
          - macos-latest
        include:
          - OS: windows-latest
            ls_options: ""

    runs-on: ${{ matrix.OS }}
    name: "ls ${{ matrix.ls_options }} @ ${{ matrix.OS }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: ./.github/actions/npm_install
        with:
          ls_options: ${{ matrix.ls_options }}

  working-directory__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        OS:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        working-directory:
          - .
          - node/sub-package

        exclude:
          # already tested
          - OS: ubuntu-latest
            working-directory: .

    runs-on: ${{ matrix.OS }}
    name: "prefix ${{ matrix.working-directory }} @ ${{ matrix.OS }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
      - uses: ./.github/actions/npm_install
        with:
          ls_options: ""
          working-directory: ${{ matrix.working-directory }}
