name: Test workflows/cmd_run

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  default:
    name: default
    uses: ./.github/workflows/cmd_run.yml

  cmd__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        cmd:
          - npm test
          - npm test --ignore-scripts
          - npm run lint
          - echo bananas

    name: "cmd: '${{ matrix.cmd }}'"
    uses: ./.github/workflows/cmd_run.yml
    with:
      cmd: ${{ matrix.cmd }}

  working-directory__matrix:
    needs: default
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        working-directory:
          - .
          - node/sub-package

        OS:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: "prefix ${{ matrix.working-directory }} @ ${{ matrix.OS }}"
    uses: ./.github/workflows/cmd_run.yml
    with:
      cmd: pwd
      runs-on: ${{ matrix.OS }}
      working-directory: ${{ matrix.working-directory }}
